### ISSUE TITLE
This vs react game kit?

### ISSUE THREAD

**Issue by Jonovono** [bberak/nature-of-code-app#1]
Can you shed some reasons on how this differs from react game kit?

Thanks!

**Comment by bberak** [comment]
Hi Jordan,

Thanks for your question.

Whilst I have never used react-game-kit, it looks like a great project with some great people behind it. I have tried to answer your question based on a quick analysis of react-game-kit's documentation.

RNGE has only two components:

- **GameLoop:** This is a simple wrapper component that fires an "onUpdate" callback every 16ms. You can use this callback to run any game-related logic and update any subcomponents as necessary. This is comparable to the Loop component in react-game-kit, however, they take this a step further and provide the ability for the Loop's subcomponents to also subscribe to the update tick. The folks at react-game-kit also provide some components that aid with physics (World, Body) and rendering (Sprite, TileMap).

- **GameEngine:** This is probably the most differentiating component - and the area where I have and will be concentrating on moving forward (albeit the lack of documentation at the moment). Whereas react-game-kit appears to take a traditional, hierarchical approach to game entity implementation (and this is not a bad thing!), the GameEngine in RNGE moves away from the OOP-based approach in favour of a Component-Entity-System paradigm. In short, this is a pattern that moves all logic out of your game's subcomponents and puts them in a series of reusable systems. Your game components become nothing more than simple data structures (no need for classes) that can be manipulated at runtime to produce interesting results. I've found it to be a great pattern for organizing games/interactive scenes and managing complexity - but that's just my opinion. This GameDev article explains it a lot more eloquently than I ever could: [Understanding CES](https://www.gamedev.net/articles/programming/general-and-gameplay-programming/understanding-component-entity-systems-r3013/)

To that extent, the GameEngine is pretty lean and provides the following:

- Normalized multi-touch event support (Start, End, Press, LongPress, Move)
- Time deltas (useful for physics engines)
- An event/signalling pipeline (useful for communicating with non-game components outside the game engine - and vice versa)
- Automatic rendering for renderable components (essentially, a rendering system)

It leaves the following to the developer:

- Creating renderers. You can use out of the box React Native components (View, Image), or [react-native-svg](https://github.com/react-native-community/react-native-svg), or [gl-react-native](https://github.com/gre/gl-react-native-v2) or even a mix of all three. I felt that the one-size-fits-all approach would place too much restriction on the designer. The examples I'm working on all use Views - but I have tried react-native-svg and think it has some great use-cases.

- Physics. There are a fair few JS-based physics engines out there - all with there pros and cons. This is another area where I felt a highly-opinionated approach would not suffice. That said, integrating physics into a CES is not too complicated. I've got an example (unpublished) that uses [Matter JS](https://github.com/liabru/matter-js).

- Motion Sensors. I felt that this would be a nice-to-have and for most use cases it would not be required. Hence, I didn't want to burden RNGE users with any native linking or additional configuration. I was also weary about any uncessary performance and battery costs. Again, it is easy to integrate into a CES and I've got an example using [react-native-sensors](https://github.com/react-native-sensors/react-native-sensors)

- Sound. I have not had a chance to look into this yet. Not sure if this will be something RNGE provides out-of-the-box or a proof-of-concept that demonstrates usage.

Finally, react-game-kit appears to work on both the web and native platforms. React-native-game-engine is focused on React Native for the time being. 

Hope that answers your question, let me know otherwise :)

**Comment by Jonovono** [comment]
Wow, thanks for the response @bberak. I'm new to game dev so this is useful. We are working on a react native app that we want to add basic multiplayer games too. I'm going to read the link you sent but it looks like your framework might be good for what we are trying to build.

Have you thought any about how you could do multiplayer games with your engine? I have been exploring https://github.com/gamestdio/colyseus/.

Thanks for the response! Will for sure give this a try as we dive into our project.

**Comment by bberak** [comment]
Sounds like an interesting project @Jonovono - I'd be more than happy to help where I can. I had a few thoughts around mutiplayer/networking support as I was developing the GameEngine component, and I think it's quite doable. Thanks for sharing Colyseus - I'll definitely check it out. My idea was to write up a crude example using [Firebase](https://firebase.google.com) since I'm semi-familiar with it.. The goods news is Firebase is based on WebSockets, just as Colyseus appears to be, so hopefully the code will be fairly adaptable.

Cheers!

**Comment by Jonovono** [comment]
Ya, I was also exploring firebase a bit. Would work too. 

Came across this which looked interesting: https://github.com/petehunt/react-multiplayer

**Comment by RWOverdijk** [comment]
For others finding this in the future (like I did), this is in the readme of react game kit:

> Maintenance Status
Archived: This project is no longer maintained by Formidable. We are no longer responding to issues or pull requests unless they relate to security concerns. We encourage interested developers to fork this project and make it their own!
