### ISSUE TITLE
Touch array is empty in iOS

### ISSUE THREAD

**Issue by qasimmehdi** [bberak/nature-of-code-app#59]
I made an app it is working on android perfectly but on iOS touches array is empty.
I'm using touch to move entities on screen. 
react-native: 0.63.2
matter-js: 0.14.2
react-native-game-engine: 1.2.0
Edit: Updated to latest version of `react-native-game-engine` still having the same issue.

**Comment by bberak** [comment]
Hi @qasimmehdi,

I suspect this has something to do with how you have styled the `GameEngine` or its parent. Are you able to strip your app of everything except the necessary styles for your game to see if that is the issue? 

You could also try running the [handbook project](https://github.com/bberak/react-native-game-engine-handbook) on your device to see if the touches are registering. In particular, the [rigid bodies](https://github.com/bberak/react-native-game-engine-handbook/tree/master/app/physics/rigid-bodies) example may be useful because it also uses MatterJS.
