### ISSUE TITLE
Entities not firing the touch event with properly id

### ISSUE THREAD

**Issue by FSPinho** [bberak/nature-of-code-app#6]
I reproduced the example on README, and looks like any touch have the `id` with value `0`. I figured out an attribute `t.event.target` that change for each touch, but it not corresponds to the entity id. What am I doing wrong?

```js
const MovePup = (entities, { touches }) => {
    touches.filter(t => t.type === "move").forEach(t => {
          console.log(t.id)
```
output:
> 0
> 0
> ...

Thanks a lot for this project. I'm a starter developer, and this is a good way to learn about game development in React Native.

**Comment by bberak** [comment]
Hi @FSPinho,

I think my example is a bit confusing (and potentially wrong).

To diagnose this - can you touch the screen with multiple fingers? I expect to see that the touch id's increase as you move more fingers since the id's should be correlated to the number of fingers on the screen.

Also, can you let me know what version of React and React Native you are running. Cheers.

**Comment by bberak** [comment]
Hi @FSPinho,

I tried a simple test with the latest version of React Native:

```
"dependencies": {
    "react": "16.3.1",
    "react-native": "0.55.4",
    "react-native-game-engine": "^0.9.3"
  }
```

It looks like the touch ID's to increase as you place more fingers on the screen. I only tested this on the simulator however.. 

Let me know if I can help further. Cheers.
