### ISSUE TITLE
What are {touches, screen, time}?

### ISSUE THREAD

**Issue by ntwn010248** [bberak/nature-of-code-app#7]
Hi, I'm a newbie of React-native.
When I traced your code from system.js, I found these variables: touches, screen, time
But I don't know how it works since you didn't import or varify them initially.
It could be a silly problem, but I want to ask what can these variables do, and how them comes from.
Thank you.
![touches](https://user-images.githubusercontent.com/34411311/40156295-35e7786a-59cb-11e8-8227-f052905aa8de.jpg)

**Comment by bberak** [comment]
Hi @ntwn010248,

I think I should explain these variables in the docs a lot better than I have..

These variables (along with the state) are passed into your systems by the game engine. They hold useful information that may or may not help you code the logic of your game. Here's a breakdown:

- **touches**: an array of user interactions touches that have occured since the last frame. This will help you respond to user touches and gestures
- **screen**: The current screen dimensions and pixel scale. This can help you with scaling and moving around your entities on the screen.
- **dispatch**: A function to dispatch events. Use this to populate the **events** array that other systems and external components can listen for.
- **events**: This contains the user generated events (see **dispatch** above)
- **time**: Contains information about the current system time and how much times has passed since the last frame. Is useful when working with physics engines and time-based motion.

Let me know if that helps!

**Comment by ntwn010248** [comment]
@bberak Thank you for these introductions~!
This is helpful, but I still have some problems.
Now i can only use the properties you have written in the codes.
May I ask you what are those variables' property?
Like {touches} has types = {'start', 'end', 'long-press', ....} and id , i want to know the details of these.

Thanks

**Comment by bberak** [comment]
Hi @ntwn010248,

So in particular, the touches array will contain events with the following **type** values:

- **start**: This event occurs when a touch interaction starts
- **end**: This occurs when a touch interaction ends
- **press**: This happens when a user places a finger on the screen and quickly pulls it away
- **long-press**: This happens when a user places a finger on the screen and leaves it there for a while
- **move**: This happens when a user moves a finger across the screen.

In addition to the **type** property, the touches also have an "event" property that gives you additional information about the touch (xy coordinates etc). I recommend doing a console.log(...) on the event to see the details of payload.

The **id** of the events indicate the finger that is used.. For example, if you place 2 fingers on the screen - you should get touch events with id 1 and 2. Three fingers on the screen should yield events with id 1, 2 and 3 etc..

The source code of this handbook project might also be a helpful resource: https://github.com/bberak/react-native-game-engine-handbook . It contains several examples on how to use the touches array in a single and multi-touch scene.
